import { DatabaseSync } from 'node:sqlite';
import { readdirSync,readFileSync,mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { api } from '../server/api.ts';
export function migrate(db){for(const name of readdirSync(new URL('../drizzle/',import.meta.url)).filter(n=>n.endsWith('.sql')).sort()){const sql=readFileSync(new URL('../drizzle/'+name,import.meta.url),'utf8');for(const part of sql.split('--> statement-breakpoint'))if(part.trim())db.exec(part);}}
export function adapter(sqlite){let queue=Promise.resolve();return {prepare(query){let params=[];const wrapped={bind(...p){params=p;return wrapped;},async first(){return sqlite.prepare(query).get(...params)||null;},async all(){return {results:sqlite.prepare(query).all(...params)};},async run(){const r=sqlite.prepare(query).run(...params);return {success:true,meta:{changes:r.changes,last_row_id:r.lastInsertRowid}};}};return wrapped;},async batch(ss){const task=queue.then(async()=>{sqlite.exec('BEGIN IMMEDIATE');try{const result=[];for(const s of ss)result.push(await s.run());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}});queue=task.catch(()=>{});return task;}};}
export function setup(){const dir=mkdtempSync(join(tmpdir(),'novelys-test-')),file=join(dir,'db.sqlite'),db=new DatabaseSync(file);db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;');migrate(db);const objects=new Map();const e={DB:adapter(db),BUCKET:{async put(k,v){objects.set(k,new Uint8Array(v));},async get(k){return objects.has(k)?{body:objects.get(k)}:null;},async delete(k){objects.delete(k);}},BOOTSTRAP_SECRET:'test-bootstrap-key',CRON_SECRET:'test-cron-key'};return {db,e,file,objects};}
export function client(e){let cookie='';const c={get cookie(){return cookie;},set cookie(v){cookie=v;},async call(path,method='GET',body,headers={}){const req=new Request('http://localhost/api'+path,{method,headers:{Origin:'http://localhost',...(cookie?{Cookie:cookie}:{}),...(body instanceof FormData?{}:{'Content-Type':'application/json'}),...headers},...(body!==undefined?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});const response=await api(req,e);const set=response.headers.get('Set-Cookie');if(set)cookie=set.split(';')[0];let data;if(response.headers.get('Content-Type')?.includes('application/json'))data=await response.json();else data=await response.arrayBuffer();return {status:response.status,data,response};}};return c;}
export const profile=(name,email)=>({first_name:name,last_name:'Test',email,phone:'0600000000',password:'Test-Password-2026!',consent:true});
