import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { Miniflare } from 'miniflare';
import { mkdtempSync,readdirSync,readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { dateKey,addDays,parisTime } from '../lib/time.ts';

test('Exécution Cloudflare Workers : D1 transactionnel, crypto et R2',async t=>{const dir=mkdtempSync(join(tmpdir(),'novelys-worker-'));const bundle=await build({stdin:{contents:"import {api} from './server/api.ts';export default {fetch:api};",resolveDir:process.cwd()},bundle:true,write:false,platform:'browser',format:'esm',external:['node:crypto']});const mf=new Miniflare({cf:false,modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-05-01',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],d1Persist:join(dir,'d1'),r2Buckets:['BUCKET'],r2Persist:join(dir,'r2'),bindings:{DEMO_MODE:'true',LOCAL_DEMO:'true',DEMO_PASSWORD:'Local-Worker-Test-2026!'}});try{const db=await mf.getD1Database('DB');for(const name of readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())for(const part of readFileSync('drizzle/'+name,'utf8').split('--> statement-breakpoint'))if(part.trim())await db.prepare(part).run();
const clients={admin:'',parent:'',family2:'',anon:''};async function call(who,path,method='GET',body){const request=new Request('http://localhost/api'+path,{method,headers:{Origin:'http://localhost',...(clients[who]?{Cookie:clients[who]}:{}),...(body instanceof FormData?{}:{'Content-Type':'application/json'})},...(body!==undefined?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});const response=await mf.dispatchFetch(request.url,{method:request.method,headers:Object.fromEntries(request.headers),...(body!==undefined?{body:new Uint8Array(await request.arrayBuffer())}:{})});if(response.headers.get('Set-Cookie'))clients[who]=response.headers.get('Set-Cookie').split(';')[0];return {status:response.status,data:response.headers.get('content-type')?.includes('application/json')?await response.json():await response.arrayBuffer(),response};}
await t.test('Données de démonstration persistantes et sessions scrypt compatibles Workers',async()=>{for(const who of ['admin','parent','family2'])assert.equal((await call(who,'/auth/demo','POST',{role:who})).status,200);assert.equal((await call('parent','/dashboard')).data.students.length,2);assert.equal((await call('family2','/dashboard')).data.students.length,1);});
let bid;const start=parisTime(addDays(dateKey(),12),'11:00');await t.test('Deux vraies requêtes concurrentes sur D1 : un seul créneau occupé',async()=>{const rs=await Promise.all([call('parent','/bookings','POST',{student_id:'demo-axel',starts_at:start,duration:60,subject:'Mathématiques'}),call('family2','/bookings','POST',{student_id:'demo-matheo',starts_at:start,duration:60,subject:'Mathématiques'})]);assert.deepEqual(rs.map(r=>r.status).sort(),[201,409]);bid=rs.find(r=>r.status===201).data.id;assert.equal((await call('admin',`/bookings/${bid}/confirm`,'POST',{})).status,200);});
await t.test('Calendrier anonyme et contraintes D1 directes',async()=>{const c=await call('anon',`/calendar?start=${start}&end=${start+86400000}&duration=60`);assert.equal(c.status,200);assert.ok(!JSON.stringify(c.data).includes('Axel'));const p=db.prepare("INSERT INTO bookings(id,student_id,starts_at,ends_at,subject,status,created_at,updated_at) VALUES('raw-conflict','demo-axel',?,?,'Mathématiques','CONFIRMED',?,?)").bind(start+1800000,start+5400000,Date.now(),Date.now());await assert.rejects(p.run(),/BOOKING_CONFLICT/);});
await t.test('Envoi multipart dans R2 et téléchargement privé authentifié',async()=>{const f=new FormData();f.set('student_id','demo-axel');f.set('file',new File(['%PDF-1.4\nWorker document\n%%EOF'],'worker.pdf',{type:'application/pdf'}));const r=await call('parent','/documents','POST',f);assert.equal(r.status,201,JSON.stringify(r.data));assert.equal((await call('parent','/documents/'+r.data.id)).status,200);assert.equal((await call('admin','/documents/'+r.data.id)).status,200);assert.equal((await call('family2','/documents/'+r.data.id)).status,404);assert.equal((await call('anon','/documents/'+r.data.id)).status,401);});
await t.test('Les données fictives ne déclenchent aucun e-mail externe',async()=>{const n=await db.prepare('SELECT count(*) n FROM email_outbox').first();assert.equal(n.n,0);});
}finally{await mf.dispose();}});
